### model
model_name_or_path: meta-llama/Llama-3.2-3B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
# deepspeed: examples/deepspeed/ds_z3_config.json # Commented out as GaLore is incompatible with DeepSpeed

### GaLore configuration
use_galore: true
galore_target: all
galore_rank: 16
galore_update_interval: 200
galore_scale: 2.0
galore_proj_type: std
galore_fused: true  # Enable fused implementation (applies optimizer updates in post-backward hooks)
galore_layerwise: false  # Setting to false as requested, internal fused implementation will be used instead

### dataset
dataset: Open-R1-Math
template: llama3
cutoff_len: 2048
# max_samples: 1000 # Optional: uncomment and set for quicker testing
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/Llama-3.2-3B/galore/sft_open_r1_math
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 128
learning_rate: 1.0e-4
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

## eval
# eval_dataset: Open-R1-Math # Optional: specify eval set if needed/available
val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 100 