### model
model_name_or_path: meta-llama/Llama-3.2-3B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full

### Momentum-Factorized SGD configuration
use_mfsgd: true      # enable the new optimiser
learning_rate_mfsgd: 0.00008  # Custom LR for MFSGD parameters
learning_rate_adamw: 8.0e-5  # Custom LR for embeddings, LM head, non-2D params
mfsgd_rank: 16
mfsgd_beta: 0.9
mfsgd_eta1: 1.0
mfsgd_eta2: 0.0
mfsgd_eps: 1.0e-8
mfsgd_nesterov: false
mfsgd_use_current_projection: false
mfsgd_use_ones_for_nonzero_s: false
mfsgd_max_value: 10000

### dataset
dataset: Open-R1-Math
template: llama3
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/Llama-3.2-3B/mfsgd/sft_open_r1_math
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 128
learning_rate: 2.0e-5 # Global fallback LR (should be overridden by group LRs)
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.0
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 100 