# inference_config.yaml
#model_name_or_path: /scratch/pxm5426/runs/lora-exploration/llama-factory-1/Llama-3.2-3B_Open-R1-Math_full_ebs128_lr1e-05
#model_name_or_path: /scratch/pxm5426/runs/lora-exploration/llama-factory-1/Llama-3.2-3B_opc_edu,opc_evol,opc_mceval,opc_pkg_full_ebs128_lr1e-05/checkpoint-500
model_name_or_path: meta-llama/Llama-3.2-3B
template: llama3
#finetuning_type: full 