### model
model_name_or_path: meta-llama/Llama-3.1-8B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json # Uncomment if using full tuning and have DeepSpeed configured

### dataset
dataset: tulu3_mixture_general # Use the key defined in dataset_info.json
template: tulu_v3
cutoff_len: 4096 # Adjust based on model and task needs
# max_samples: 1000 # Optional: for quick testing
overwrite_cache: true
preprocessing_num_workers: 12

### output
output_dir: saves/Llama-3.1-8B/tulu3-sft/general # Category-specific output
logging_steps: 10
save_strategy: steps
save_steps: 300 # Adjust based on dataset size and desired frequency
eval_strategy: "no"
# eval_steps: 500 # Adjust frequency
# per_device_eval_batch_size: 2
plot_loss: true
overwrite_output_dir: false
report_to: wandb

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 32
learning_rate: 5.0e-6
num_train_epochs: 1.0 # Adjust based on category dataset size
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000

# ### eval
# val_size: 0.01 # Use a small validation set from the filtered data 